# Generated by Django 6.0.1 on 2026-01-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Asunción - CDE (Directo)', max_length=100, verbose_name='Nombre del itinerario')),
                ('ruta', models.CharField(blank=True, help_text='Código de ruta nacional (Ej: PY02, PY03)', max_length=20, null=True, verbose_name='Ruta')),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia total (km)')),
                ('duracion_estimada_hs', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Duración estimada (horas)')),
                ('dias_semana', models.CharField(help_text='Patrón binario: 1111100 = L-V, 1111111 = Todos', max_length=7, verbose_name='Días de la semana')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('orden', models.PositiveSmallIntegerField(help_text='Posición de la parada en la secuencia (1, 2, 3...)', verbose_name='Orden')),
                ('minutos_desde_origen', models.PositiveIntegerField(blank=True, help_text='Para calcular ETA. Ej: 0, 120, 300', null=True, verbose_name='Minutos desde origen')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_itinerario', to='fleet.parada', verbose_name='Parada')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='itineraries.itinerario', verbose_name='Itinerario')),
            ],
            options={
                'verbose_name': 'Detalle de itinerario',
                'verbose_name_plural': 'Detalles de itinerario',
                'ordering': ['itinerario', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('itinerario', 'orden'), name='unique_orden_por_itinerario'), models.UniqueConstraint(fields=('itinerario', 'parada'), name='unique_parada_por_itinerario')],
                'unique_together': {('itinerario', 'orden'), ('itinerario', 'parada')},
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del pasaje en guaraníes', max_digits=12, verbose_name='Precio')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_como_destino', to='fleet.parada', verbose_name='Parada destino')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='itineraries.itinerario', verbose_name='Itinerario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precios_como_origen', to='fleet.parada', verbose_name='Parada origen')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['itinerario', 'origen', 'destino'],
                'constraints': [models.UniqueConstraint(fields=('itinerario', 'origen', 'destino'), name='unique_precio_por_tramo')],
                'unique_together': {('itinerario', 'origen', 'destino')},
            },
        ),
    ]
