# Generated by Django 6.0.1 on 2026-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleitinerario',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
    ]
