# Generated by Django 6.0.1 on 2026-03-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_detalleitinerario_hora_llegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleitinerario',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='detalleitinerario',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='detalleitinerario',
            name='distancia_desde_origen_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia desde origen (km)'),
        ),
        migrations.AlterField(
            model_name='detalleitinerario',
            name='minutos_desde_origen',
            field=models.PositiveIntegerField(default=0, help_text='Minutos estimados desde la primera parada. Ej: 0, 30, 60, 120', verbose_name='Minutos desde origen'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(help_text='Hora en que el bus parte de la primera parada', verbose_name='Hora de salida programada')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='itineraries.itinerario', verbose_name='Itinerario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['itinerario', 'hora_salida'],
                'constraints': [models.UniqueConstraint(fields=('itinerario', 'hora_salida'), name='unique_horario_por_itinerario')],
                'unique_together': {('itinerario', 'hora_salida')},
            },
        ),
    ]
