# Generated by Django 6.0.1 on 2026-03-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('itineraries', '0003_remove_detalleitinerario_hora_llegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='fleet.empresa', verbose_name='Empresa'),
        ),
    ]
