# Generated by Django 6.0.1 on 2026-04-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('itineraries', '0004_itinerario_empresa'),
        ('users', '0004_persona_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ayudante_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('es_ayudante', True), ('es_empleado', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_como_ayudante_pred', to='users.persona', verbose_name='Ayudante predeterminado'),
        ),
        migrations.AddField(
            model_name='horario',
            name='bus_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_predeterminados', to='fleet.bus', verbose_name='Bus predeterminado'),
        ),
        migrations.AddField(
            model_name='horario',
            name='chofer_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('es_chofer', True), ('es_empleado', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_como_chofer_pred', to='users.persona', verbose_name='Chofer predeterminado'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='ayudante_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('es_ayudante', True), ('es_empleado', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerarios_como_ayudante_pred', to='users.persona', verbose_name='Ayudante predeterminado'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='bus_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerarios_predeterminados', to='fleet.bus', verbose_name='Bus predeterminado'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='chofer_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('es_chofer', True), ('es_empleado', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerarios_como_chofer_pred', to='users.persona', verbose_name='Chofer predeterminado'),
        ),
    ]
