# Generated by Django 6.0.1 on 2026-04-22 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_horario_ayudante_predeterminado_and_more'),
        ('users', '0006_persona_latitud_persona_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ayudante_predeterminado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bus_predeterminado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='chofer_predeterminado',
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='ayudante_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_ayudante': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerarios_como_ayudante_pred', to='users.persona', verbose_name='Ayudante predeterminado'),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='chofer_predeterminado',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_chofer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerarios_como_chofer_pred', to='users.persona', verbose_name='Chofer predeterminado'),
        ),
    ]
