# Generated by Django 6.0.1 on 2026-05-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_remove_horario_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['hora_salida'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveConstraint(
            model_name='horario',
            name='unique_horario_por_itinerario',
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('hora_salida',)},
        ),
        migrations.AddField(
            model_name='itinerario',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='itinerarios', to='itineraries.horario', verbose_name='Horarios de salida'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_salida',
            field=models.TimeField(help_text='Hora de salida', verbose_name='Hora de salida'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('hora_salida',), name='unique_horario_salida'),
        ),
        migrations.RemoveField(
            model_name='horario',
            name='itinerario',
        ),
    ]
