# Generated by Django 6.0.1 on 2026-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('itineraries', '0007_alter_horario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precio',
            options={'ordering': ['origen', 'destino'], 'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
        migrations.RemoveConstraint(
            model_name='precio',
            name='unique_precio_por_tramo',
        ),
        migrations.AlterUniqueTogether(
            name='precio',
            unique_together={('origen', 'destino')},
        ),
        migrations.AddConstraint(
            model_name='precio',
            constraint=models.UniqueConstraint(fields=('origen', 'destino'), name='unique_precio_por_tramo_global'),
        ),
        migrations.RemoveField(
            model_name='precio',
            name='itinerario',
        ),
    ]
