# Generated by Django 6.0.1 on 2026-01-25 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada latitud (ej: -25.2867)', max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada longitud (ej: -57.3333)', max_digits=9, null=True, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.BigIntegerField(help_text='Número de cédula de identidad', primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('es_empleado', models.BooleanField(default=False, verbose_name='Es empleado')),
                ('es_cliente', models.BooleanField(default=False, verbose_name='Es cliente')),
                ('es_pasajero', models.BooleanField(default=False, verbose_name='Es pasajero')),
                ('user', models.OneToOneField(blank=True, help_text='Relación opcional con cuenta de usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
