# Generated by Django 6.0.1 on 2026-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_ayudante',
            field=models.BooleanField(default=False, verbose_name='Es ayudante de transporte'),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_chofer',
            field=models.BooleanField(default=False, verbose_name='Es chofer'),
        ),
    ]
