# Generated by Django 6.0.1 on 2026-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_persona_es_ayudante_persona_es_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
