# Generated by Django 6.0.1 on 2026-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('users', '0003_alter_localidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece (choferes/ayudantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='fleet.empresa', verbose_name='Empresa'),
        ),
    ]
