# Generated by Django 6.0.1 on 2026-04-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_persona_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='es_pasajero',
        ),
    ]
