# Generated by Django 6.0.1 on 2026-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_persona_es_pasajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada latitud de la dirección', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='persona',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada longitud de la dirección', max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
