# Generated by Django 6.0.1 on 2026-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_persona_latitud_persona_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
