# Generated by Django 6.0.1 on 2026-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_persona_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_agente',
            field=models.BooleanField(default=False, verbose_name='Es agente comercial'),
        ),
    ]
