# Generated by Django 6.0.1 on 2026-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_persona_es_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(help_text='Número de cédula de identidad o RUC (ej: 1234567-8)', max_length=20, primary_key=True, serialize=False, verbose_name='Cédula/RUC'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='es_empleado',
            field=models.BooleanField(default=False, verbose_name='Es empleado (Legacy)'),
        ),
    ]
