# Generated by Django 6.0.1 on 2026-07-09 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_persona_cedula_alter_persona_es_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(help_text='Número de cédula de identidad o RUC (ej: 1234567 o 1234567-8)', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números, opcionalmente seguidos de un guion y un dígito (ej: 1234567 o 1234567-8).', regex='^\\d+(-\\d)?$')], verbose_name='Cédula/RUC'),
        ),
    ]
