# Generated by Django 6.0.1 on 2026-01-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la empresa')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyente', max_length=20, unique=True, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('direccion_legal', models.TextField(blank=True, null=True, verbose_name='Dirección legal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Número de placa del vehículo', max_length=20, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('capacidad_pisos', models.PositiveSmallIntegerField(default=1, help_text='Número de pisos del bus (1 o 2)', verbose_name='Cantidad de pisos')),
                ('capacidad_asientos', models.PositiveIntegerField(help_text='Número total de asientos del bus', verbose_name='Capacidad de asientos')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='fleet.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['empresa', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Terminal de Oviedo', max_length=200, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('latitud_gps', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud GPS')),
                ('longitud_gps', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud GPS')),
                ('es_sucursal', models.BooleanField(default=False, help_text='Indica si esta parada es una sucursal de la empresa', verbose_name='Es sucursal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='fleet.empresa', verbose_name='Empresa')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='users.localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['empresa', 'localidad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveSmallIntegerField(verbose_name='Número de asiento')),
                ('piso', models.PositiveSmallIntegerField(default=1, help_text='Piso donde se encuentra el asiento (1 o 2)', verbose_name='Piso')),
                ('tipo_asiento', models.CharField(choices=[('cama', 'Cama'), ('semi_cama', 'Semi-Cama'), ('convencional', 'Convencional')], default='convencional', max_length=20, verbose_name='Tipo de asiento')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='fleet.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['bus', 'piso', 'numero_asiento'],
                'constraints': [models.UniqueConstraint(fields=('bus', 'numero_asiento'), name='unique_asiento_por_bus')],
                'unique_together': {('bus', 'numero_asiento')},
            },
        ),
    ]
