# Generated by Django 6.0.1 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='es_sucursal',
        ),
        migrations.AddField(
            model_name='parada',
            name='es_agencia',
            field=models.BooleanField(default=False, help_text='Indica si esta parada es una agencia de la empresa', verbose_name='Es agencia'),
        ),
    ]
