# Generated by Django 6.0.1 on 2026-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_parada_es_sucursal_parada_es_agencia'),
        ('users', '0003_alter_localidad_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('empresa', 'localidad', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='parada',
            constraint=models.UniqueConstraint(fields=('empresa', 'localidad', 'nombre'), name='unique_parada_por_empresa'),
        ),
    ]
