# Generated by Django 6.0.1 on 2026-06-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='numero_bus',
            field=models.CharField(blank=True, help_text='Número o código identificador del bus (ej: 05, C-12)', max_length=20, null=True, verbose_name='Número de bus'),
        ),
    ]
