# Generated by Django 6.0.1 on 2026-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_bus_numero_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la parada está activa o inactiva', verbose_name='Activa'),
        ),
    ]
