# Generated by Django 6.0.1 on 2026-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_parada_activo'),
        ('users', '0010_alter_persona_cedula'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parada',
            name='unique_parada_por_empresa',
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('empresa', 'localidad')},
        ),
        migrations.AddConstraint(
            model_name='parada',
            constraint=models.UniqueConstraint(fields=('empresa', 'localidad'), name='unique_parada_por_empresa_localidad'),
        ),
    ]
