# Generated by Django 6.0.1 on 2026-02-04 22:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('itineraries', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paquete', 'Paquete'), ('documento', 'Documento'), ('valija', 'Valija'), ('carga', 'Carga')], default='paquete', max_length=20, verbose_name='Tipo de encomienda')),
                ('descripcion', models.TextField(verbose_name='Descripción del contenido')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_transito', 'En Tránsito'), ('en_destino', 'En Destino'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='registrado', max_length=20, verbose_name='Estado')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de seguimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('receptor_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de quien recibe')),
                ('receptor_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula de quien recibe')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_recibidas', to='users.persona', verbose_name='Destinatario')),
                ('parada_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_destino', to='fleet.parada', verbose_name='Parada de destino')),
                ('parada_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_origen', to='fleet.parada', verbose_name='Parada de origen')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_enviadas', to='users.persona', verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.BigIntegerField(verbose_name='Número de factura')),
                ('condicion', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Condición de venta')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('subtotal_exenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal exenta')),
                ('subtotal_iva5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal IVA 5%')),
                ('subtotal_iva10', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal IVA 10%')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total')),
                ('iva_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IVA 5%')),
                ('iva_10', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IVA 10%')),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total IVA')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=10, verbose_name='Estado')),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='users.persona', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('vendido', 'Vendido'), ('abordado', 'Abordado'), ('cancelado', 'Cancelado'), ('no_show', 'No se presentó')], default='reservado', max_length=20, verbose_name='Estado')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de pasaje')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes', to='fleet.asiento', verbose_name='Asiento')),
                ('cliente', models.ForeignKey(blank=True, help_text='Si es el mismo que el pasajero, dejar vacío', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pasajes_comprados', to='users.persona', verbose_name='Cliente (quien paga)')),
                ('parada_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes_destino', to='fleet.parada', verbose_name='Parada de destino')),
                ('parada_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes_origen', to='fleet.parada', verbose_name='Parada de origen')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes', to='users.persona', verbose_name='Pasajero')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pasaje',
                'verbose_name_plural': 'Pasajes',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio unitario')),
                ('tasa_iva', models.IntegerField(choices=[(0, 'Exenta'), (5, 'IVA 5%'), (10, 'IVA 10%')], default=10, verbose_name='Tasa de IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('encomienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_factura', to='operations.encomienda', verbose_name='Encomienda relacionada')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operations.factura', verbose_name='Factura')),
                ('pasaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_factura', to='operations.pasaje', verbose_name='Pasaje relacionado')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('monto_cierre_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de cierre esperado')),
                ('monto_cierre_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de cierre real')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Diferencia')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Sesión de caja',
                'verbose_name_plural': 'Sesiones de caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('concepto', models.CharField(choices=[('venta_pasaje', 'Venta de pasaje'), ('venta_encomienda', 'Venta de encomienda'), ('anulacion', 'Anulación'), ('devolucion', 'Devolución'), ('gasto', 'Gasto'), ('retiro', 'Retiro'), ('deposito', 'Depósito'), ('otro', 'Otro')], max_length=20, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='operations.factura', verbose_name='Factura relacionada')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='operations.sesioncaja', verbose_name='Sesión de caja')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='operations.sesioncaja', verbose_name='Sesión de caja'),
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número de timbrado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de vigencia')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin de vigencia')),
                ('numero_desde', models.BigIntegerField(verbose_name='Número de factura desde')),
                ('numero_hasta', models.BigIntegerField(verbose_name='Número de factura hasta')),
                ('punto_expedicion', models.CharField(help_text='Ej: 001-001', max_length=10, verbose_name='Punto de expedición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbrados', to='fleet.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='operations.timbrado', verbose_name='Timbrado'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField(verbose_name='Fecha del viaje')),
                ('hora_salida_real', models.TimeField(blank=True, null=True, verbose_name='Hora de salida real')),
                ('hora_llegada_real', models.TimeField(blank=True, null=True, verbose_name='Hora de llegada real')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='fleet.bus', verbose_name='Bus')),
                ('chofer', models.ForeignKey(limit_choices_to={'es_empleado': True}, on_delete=django.db.models.deletion.PROTECT, related_name='viajes_como_chofer', to='users.persona', verbose_name='Chofer')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='itineraries.itinerario', verbose_name='Itinerario')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_viaje', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidad (km/h)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('eta_proxima_parada', models.DateTimeField(blank=True, null=True, verbose_name='ETA próxima parada')),
                ('parada_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackings', to='fleet.parada', verbose_name='Parada actual o próxima')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='operations.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Tracking de viaje',
                'verbose_name_plural': 'Trackings de viajes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='pasaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasajes', to='operations.viaje', verbose_name='Viaje'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mecanico', 'Problema Mecánico'), ('accidente', 'Accidente'), ('retraso', 'Retraso'), ('pasajero', 'Incidente con Pasajero'), ('clima', 'Condiciones Climáticas'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta')], default='abierta', max_length=15, verbose_name='Estado')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('resolucion', models.TextField(blank=True, null=True, verbose_name='Resolución')),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='operations.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddField(
            model_name='encomienda',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='operations.viaje', verbose_name='Viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('timbrado', 'numero_factura')},
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('itinerario', 'bus', 'fecha_viaje'), name='unique_viaje_por_dia'),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together={('itinerario', 'bus', 'fecha_viaje')},
        ),
        migrations.AddConstraint(
            model_name='pasaje',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['reservado', 'vendido', 'abordado'])), fields=('viaje', 'asiento'), name='unique_asiento_por_viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='pasaje',
            unique_together={('viaje', 'asiento')},
        ),
    ]
