# Generated by Django 6.0.1 on 2026-03-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('users', '0002_persona_es_ayudante_persona_es_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='ayudantes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('es_ayudante', True), ('es_empleado', True), _connector='OR'), related_name='viajes_como_ayudante', to='users.persona', verbose_name='Ayudantes'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(limit_choices_to=models.Q(('es_chofer', True), ('es_empleado', True), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='viajes_como_chofer', to='users.persona', verbose_name='Chofer'),
        ),
    ]
