# Generated by Django 6.0.1 on 2026-03-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_parada_es_sucursal_parada_es_agencia'),
        ('itineraries', '0003_remove_detalleitinerario_hora_llegada_and_more'),
        ('operations', '0002_viaje_ayudantes_alter_viaje_chofer'),
        ('users', '0002_persona_es_ayudante_persona_es_chofer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pasaje',
            name='unique_asiento_por_viaje',
        ),
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_viaje_por_dia',
        ),
        migrations.AlterUniqueTogether(
            name='pasaje',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='viaje',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='orden_destino',
            field=models.PositiveSmallIntegerField(default=2, help_text='Posición ordinal de la parada destino en el itinerario', verbose_name='Orden parada destino'),
        ),
        migrations.AddField(
            model_name='pasaje',
            name='orden_origen',
            field=models.PositiveSmallIntegerField(default=1, help_text='Posición ordinal de la parada origen en el itinerario', verbose_name='Orden parada origen'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(blank=True, help_text='El horario programado para esta salida', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='itineraries.horario', verbose_name='Horario de salida'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('itinerario', 'horario', 'fecha_viaje'), name='unique_viaje_por_horario_dia'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('bus', 'horario', 'fecha_viaje'), name='unique_bus_por_horario_dia'),
        ),
    ]
