# Generated by Django 6.0.1 on 2026-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('itineraries', '0003_remove_detalleitinerario_hora_llegada_and_more'),
        ('operations', '0003_remove_pasaje_unique_asiento_por_viaje_and_more'),
        ('users', '0003_alter_localidad_nombre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(fields=('chofer', 'itinerario', 'fecha_viaje'), name='unique_chofer_por_itinerario_dia'),
        ),
    ]
