# Generated by Django 6.0.1 on 2026-03-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_parada_unique_together_and_more'),
        ('operations', '0004_viaje_unique_chofer_por_itinerario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='fleet.empresa', verbose_name='Empresa'),
        ),
    ]
