# Generated by Django 6.0.1 on 2026-04-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_viaje_empresa'),
        ('users', '0004_persona_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, help_text='Para reservas: fecha/hora límite para abonar el pasaje', null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.CreateModel(
            name='UbicacionAyudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidad (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dirección (grados)')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='users.persona', verbose_name='Persona')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_personal', to='operations.viaje', verbose_name='Viaje en curso')),
            ],
            options={
                'verbose_name': 'Ubicación de ayudante',
                'verbose_name_plural': 'Ubicaciones de ayudantes',
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('persona',), name='unique_ubicacion_activa_por_persona')],
            },
        ),
    ]
