# Generated by Django 6.0.1 on 2026-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_pasaje_fecha_limite_pago_ubicacionayudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='codigo',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de pasaje'),
        ),
    ]
