# Generated by Django 6.0.1 on 2026-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_pasaje_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del tramo'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de pasaje'),
        ),
    ]
