# Generated by Django 6.0.1 on 2026-05-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_pasaje_descripcion_alter_pasaje_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes_vendidos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
