# Generated by Django 6.0.1 on 2026-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_pasaje_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='fecha_en_destino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en destino'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_en_transito',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en tránsito'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('en_transito', 'En Tránsito'), ('en_destino', 'Entregada en Destino'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='registrado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='tipo',
            field=models.CharField(choices=[('sobre', 'Sobre / Paquete Pequeño'), ('mediano', 'Paquete Mediano'), ('grande', 'Paquete Grande')], default='paquete', max_length=20, verbose_name='Tipo de encomienda'),
        ),
    ]
