# Generated by Django 6.0.1 on 2026-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_encomienda_fecha_en_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='reservas_bloqueadas',
            field=models.BooleanField(default=False, help_text='Bloquear la posibilidad de reservar asientos (indicando que el bus está lleno)', verbose_name='Reservas Bloqueadas'),
        ),
    ]
