# Generated by Django 6.0.1 on 2026-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_viaje_reservas_bloqueadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='tipo',
            field=models.CharField(choices=[('sobre', 'Sobre / Paquete Pequeño'), ('mediano', 'Paquete Mediano'), ('grande', 'Paquete Grande')], default='sobre', max_length=20, verbose_name='Tipo de encomienda'),
        ),
    ]
