# Generated by Django 6.0.1 on 2026-05-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_encomienda_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasaje',
            options={'ordering': ['-id'], 'verbose_name': 'Pasaje', 'verbose_name_plural': 'Pasajes'},
        ),
    ]
