# Generated by Django 6.0.1 on 2026-05-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_alter_pasaje_options'),
        ('users', '0008_persona_es_agente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ayudantes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('es_ayudante', True)), related_name='viajes_como_ayudante', to='users.persona', verbose_name='Ayudantes'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(limit_choices_to=models.Q(('es_chofer', True)), on_delete=django.db.models.deletion.PROTECT, related_name='viajes_como_chofer', to='users.persona', verbose_name='Chofer'),
        ),
    ]
