# Generated by Django 6.0.1 on 2026-07-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_alter_viaje_ayudantes_alter_viaje_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='receptor_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de quien recibe'),
        ),
    ]
