# Generated by Django 6.0.1 on 2026-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_parada_activo'),
        ('itineraries', '0008_alter_precio_options_and_more'),
        ('operations', '0015_encomienda_receptor_telefono'),
        ('users', '0009_alter_persona_cedula_alter_persona_es_empleado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_viaje_por_horario_dia',
        ),
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_bus_por_horario_dia',
        ),
        migrations.RemoveConstraint(
            model_name='viaje',
            name='unique_chofer_por_itinerario_dia',
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('itinerario', 'horario', 'fecha_viaje'), name='unique_viaje_por_horario_dia'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('bus', 'horario', 'fecha_viaje'), name='unique_bus_por_horario_dia'),
        ),
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('chofer', 'itinerario', 'fecha_viaje'), name='unique_chofer_por_itinerario_dia'),
        ),
    ]
